# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add permissions block at the workflow level
permissions:
  contents: write
  packages: write

jobs:
  bump-version:
    name: "Bump Version"
    runs-on: ubuntu-latest
    # Add permissions for this specific job
    permissions:
      contents: write

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: '2'
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Automated Version Bump"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          oldVersion=$(echo $(git show $(git log --first-parent -1 --skip 1 --pretty=format:"%H"):package.json) | jq -r ".version")
          echo "$oldVersion"
          IFS='.' read -r -a versionArray <<< "$oldVersion"
          ((versionArray[2]=versionArray[2]+1))
          newVersion="${versionArray[@]}"
          newVersion=${newVersion// /.}
          npm version "$newVersion"
          git push origin ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        
  build-exe:
    name: "Build Quadrator"
    runs-on: windows-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3
      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: "npm install"
        run: npm install
      - name: "Build .exe"
        continue-on-error: true
        run: |
          npm run electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Parse version"
        run: |
          echo "Q_VERSION=$(jq -r .version package.json)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Archive .exe
        uses: actions/upload-artifact@v4
        with:
          name: Quadrator-${{env.Q_VERSION}}
          path: |
            dist_electron/*.exe
